### ISSUE TITLE
Good bye golf ball

### ISSUE THREAD

**Issue by brandonjnelsonFDA** [bnel1201/PedSilicoICH#56]
Improve the realism of the intraparenchymal (sphere) lesion

**Comment by brandonjnelsonFDA** [comment]
In addition to implementing a more natural intraparenchymal hemorrhage shape, let's also implement the [mass effect code ](https://github.com/brandonjnelsonFDA/PedSilicoICH/blob/4fa3d015d0e3e6199bb9d98fa04dcf69260e6032/src/pedsilicoICH/lesion_definition.py#L181 )currently used in the epidural and subdural lesions and recently adapted by @malago86 for the Victre phantom for our intraparenchymal round lesions

Here's the Victre example from Miguel:
![image](https://github.com/user-attachments/assets/16c72f3a-e094-48e3-a9da-7dc02bbb9d4d)

**Comment by brandonjnelsonFDA** [comment]
Consider using a combination of scikit-images [ellipsoid function](https://scikit-image.org/docs/stable/api/skimage.draw.html#skimage.draw.ellipsoid) with [albumentations non-rigid transforms](https://albumentations.ai/docs/examples/example_kaggle_salt/#non-rigid-transformations-elastictransform-griddistortion-opticaldistortion) to get some more interesting shapes that aren't perfect spheres

Also consider adapting some of Shueyue's segmentation augmentation code:

- [MISS-tool/spike](https://github.com/DIDSR/MISS-tool/blob/main/mod_spike.m)
- [MISS-tool/fourier](https://github.com/DIDSR/MISS-tool/blob/main/mod_fourier.m)

Also also consider adapting [VictrePipeline/breastMass](https://github.com/DIDSR/breastMass)

**Comment by brandonjnelsonFDA** [comment]
Also use [distance transform](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.distance_transform_edt.html#distance-transform-edt) combined with a threshold of the lesion radius or half the bounding box to speed up the insertion time by only selecting from center points where the lesion can be fit rather than allowing center points in tiny white matter spicules where only the smallest lesions could fit.

**Comment by brandonjnelsonFDA** [comment]
To summarize these are the proposed fixes:
1. [ ] introduce more assymetric/natural shapes using a [couple of potential options](https://github.com/brandonjnelsonFDA/PedSilicoICH/issues/56#issuecomment-2409950785)
 - introduced elliptic lesions e3a614e94682ef0e2329fe8558a8f11a38668332
 - introduced random rotations of elliptic lesions in dba23d94a2d9444965d464c41cd69a4b6eec08a4, but still need to introduce more data augmentations
3. [X] Use a [thresholded distance transform](https://github.com/brandonjnelsonFDA/PedSilicoICH/issues/56#issuecomment-2411411479) to speed up random insertion time - introduced in commit db1babaf32382bbd7b13b51409d75cc484ff04cb
4. [X] add [mass effect processing](https://github.com/brandonjnelsonFDA/PedSilicoICH/issues/56#issuecomment-2407828579) to this lesion type rather than simply replacing voxels - introduced in dba23d94a2d9444965d464c41cd69a4b6eec08a4

**Comment by brandonjnelsonFDA** [comment]
Added mass effect and random rotations in this recent commit: dba23d94a2d9444965d464c41cd69a4b6eec08a4

This might be the end of this issue for now as more sophisticated intraparenchymal lesions may be saved for a later issue.

One last thing I may try is adding a few random ellipses via OR operations to make a slightly more complicated shape.

Future work could include shape
analysis of real IPH that would better inform our models

**Comment by brandonjnelsonFDA** [comment]
The recent addition of complexity and edema as round lesion parameters gets our synthetic round lesions closer to some of the examples in [Hillal 2021](https://insightsimaging.springeropen.com/articles/10.1186/s13244-022-01309-1), future work (saved for another issue) can seek to add more non-uniform texture and heterogeneity which is also indicative of time since injury.

Recent complex lesion with edema example (in phantom space, not yet imaged)
![image](https://github.com/user-attachments/assets/d5a1be9e-e68d-403f-8b4a-78cbd95e8ba8)

And here are examples trimmed from [Hillal 2021](https://insightsimaging.springeropen.com/articles/10.1186/s13244-022-01309-1) fig 1 and 2 respectively.
![image](https://github.com/user-attachments/assets/24b92b55-201b-4602-8146-d2295fcb223b)
![image](https://github.com/user-attachments/assets/f692887c-c88f-4d09-8b15-a6ca53a2fa0d)

But this issue can now be closed for now with the merging of https://github.com/brandonjnelsonFDA/PedSilicoICH/pull/60 into master
